<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>R Notebook</title>

<script src="PA1_template_files/header-attrs-2.11/header-attrs.js"></script>
<script src="PA1_template_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="PA1_template_files/navigation-1.1/tabsets.js"></script>
<link href="PA1_template_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="PA1_template_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div id="header">



<h1 class="title toc-ignore">R Notebook</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#preprocessing-the-data"><span class="toc-section-number">0.0.1</span> PREPROCESSING THE DATA</a></li>
<li><a href="#plotting-the-data"><span class="toc-section-number">0.0.2</span> PLOTTING THE DATA</a></li>
<li><a href="#filling-nas"><span class="toc-section-number">0.0.3</span> FILLING NA’S</a></li>
</ul>
</div>

<p>In this document, personal movement data will be analysed in exploratory way. The data is about taken steps in 61 days.</p>
<div id="preprocessing-the-data" class="section level3" number="0.0.1">
<h3><span class="header-section-number">0.0.1</span> PREPROCESSING THE DATA</h3>
<p>Let’s unzip our dataset.</p>
<pre class="r"><code>unzip(&quot;./activity.zip&quot;, exdir = getwd())</code></pre>
<p>This is a comma seperated file. So we create our dataframe and deploy it in the variable data.</p>
<pre class="r"><code>curr_locale &lt;- Sys.getlocale(&quot;LC_TIME&quot;)
Sys.setlocale(&quot;LC_TIME&quot;,&quot;en_US.UTF-8&quot;)</code></pre>
<pre><code>## Warning in Sys.setlocale(&quot;LC_TIME&quot;, &quot;en_US.UTF-8&quot;): İşletim Sistemi yereli
## &quot;en_US.UTF-8&quot; e ayarlama isteğinin gerçekleştirelemeyeceğini raporladı</code></pre>
<pre><code>## [1] &quot;&quot;</code></pre>
<pre class="r"><code>Sys.setlocale(&quot;LC_TIME&quot;,curr_locale)</code></pre>
<pre><code>## [1] &quot;Turkish_Turkey.1254&quot;</code></pre>
<pre class="r"><code>dev_null &lt;- Sys.setlocale(&quot;LC_TIME&quot;, &quot;english&quot;)
data &lt;- read.csv(&#39;./activity.csv&#39;, sep = &quot;,&quot;)</code></pre>
<p>Let’s have a look of the first observations of the data.</p>
<pre class="r"><code>head(data)</code></pre>
<pre><code>##   steps       date interval
## 1    NA 2012-10-01        0
## 2    NA 2012-10-01        5
## 3    NA 2012-10-01       10
## 4    NA 2012-10-01       15
## 5    NA 2012-10-01       20
## 6    NA 2012-10-01       25</code></pre>
<p>In the dataset there is a column named steps which we are interested mostly. It seems there are NA’s in our data. And there is a date column and interval column. So our dataset is kind of a timeseries dataset. Let’s have a look of structure of the data.</p>
<pre class="r"><code>str(data)</code></pre>
<pre><code>## &#39;data.frame&#39;:    17568 obs. of  3 variables:
##  $ steps   : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ date    : chr  &quot;2012-10-01&quot; &quot;2012-10-01&quot; &quot;2012-10-01&quot; &quot;2012-10-01&quot; ...
##  $ interval: int  0 5 10 15 20 25 30 35 40 45 ...</code></pre>
<p>Date is deployed as character and others are integers. And dimension of our data:</p>
<pre class="r"><code>dim(data)</code></pre>
<pre><code>## [1] 17568     3</code></pre>
<p>We know we have NA values, and how many values are NA?</p>
<pre class="r"><code>colSums(is.na(data))</code></pre>
<pre><code>##    steps     date interval 
##     2304        0        0</code></pre>
<p>Son only steps column has NAs. What about the ratio of NA values?</p>
<pre class="r"><code>sum(is.na(data$steps))/length(data$steps)</code></pre>
<pre><code>## [1] 0.1311475</code></pre>
<p>Now let’s transform our date column from char to “YYMMDD” date format and create a new column as factor that shows which weekday is the date. So we will be able to have opinions of subject’s behaviour in weekdays.</p>
<pre class="r"><code>data$date &lt;- as.Date(data$date)

data$weekday &lt;- as.factor(weekdays(data$date))

summary(data)</code></pre>
<pre><code>##      steps             date               interval           weekday    
##  Min.   :  0.00   Min.   :2012-10-01   Min.   :   0.0   Friday   :2592  
##  1st Qu.:  0.00   1st Qu.:2012-10-16   1st Qu.: 588.8   Monday   :2592  
##  Median :  0.00   Median :2012-10-31   Median :1177.5   Saturday :2304  
##  Mean   : 37.38   Mean   :2012-10-31   Mean   :1177.5   Sunday   :2304  
##  3rd Qu.: 12.00   3rd Qu.:2012-11-15   3rd Qu.:1766.2   Thursday :2592  
##  Max.   :806.00   Max.   :2012-11-30   Max.   :2355.0   Tuesday  :2592  
##  NA&#39;s   :2304                                           Wednesday:2592</code></pre>
</div>
<div id="plotting-the-data" class="section level3" number="0.0.2">
<h3><span class="header-section-number">0.0.2</span> PLOTTING THE DATA</h3>
<p>Now we have a better form of data and let’s take a look in which day our subjects have more steps? First we make groups to see steps taken each day.</p>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>steps_by_days &lt;- aggregate(data$steps, by=list(date = data$date), FUN=sum, na.rm=TRUE)
names(steps_by_days) &lt;- c(&quot;Date&quot;,&quot;Total_Steps&quot;)</code></pre>
<p>Now we have a group of dates. Let’s take a look at the plot of steps taken in days.</p>
<pre class="r"><code>library(ggplot2)

g &lt;- ggplot(steps_by_days,aes(Date,Total_Steps))
g + geom_col(aes(colour=Date))  +scale_x_date(date_breaks = &quot;5 days&quot;, date_labels = &quot;%d.%m&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>It looks like we have maximum steps number in date 23.11. And probably because of NA values we have zero bars. Let’s find average value of steps taken in days in same way of grouping.</p>
<pre class="r"><code>mean_by_days &lt;- aggregate(data$steps, by=list(weekday = data$date), FUN = mean, na.rm=TRUE)</code></pre>
<pre class="r"><code>names(mean_by_days) &lt;- c(&quot;Date&quot;,&quot;Mean&quot;)</code></pre>
<pre class="r"><code>g &lt;- ggplot(mean_by_days,aes(Date, Mean))
g + geom_col(aes(colour=Date))  +scale_x_date(date_breaks = &quot;5 days&quot;, date_labels = &quot;%d.%m&quot;)</code></pre>
<pre><code>## Warning: Removed 8 rows containing missing values (position_stack).</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>And the median of steps in each days:</p>
<pre class="r"><code>tapply(data$steps, data$date, median)</code></pre>
<pre><code>## 2012-10-01 2012-10-02 2012-10-03 2012-10-04 2012-10-05 2012-10-06 2012-10-07 
##         NA          0          0          0          0          0          0 
## 2012-10-08 2012-10-09 2012-10-10 2012-10-11 2012-10-12 2012-10-13 2012-10-14 
##         NA          0          0          0          0          0          0 
## 2012-10-15 2012-10-16 2012-10-17 2012-10-18 2012-10-19 2012-10-20 2012-10-21 
##          0          0          0          0          0          0          0 
## 2012-10-22 2012-10-23 2012-10-24 2012-10-25 2012-10-26 2012-10-27 2012-10-28 
##          0          0          0          0          0          0          0 
## 2012-10-29 2012-10-30 2012-10-31 2012-11-01 2012-11-02 2012-11-03 2012-11-04 
##          0          0          0         NA          0          0         NA 
## 2012-11-05 2012-11-06 2012-11-07 2012-11-08 2012-11-09 2012-11-10 2012-11-11 
##          0          0          0          0         NA         NA          0 
## 2012-11-12 2012-11-13 2012-11-14 2012-11-15 2012-11-16 2012-11-17 2012-11-18 
##          0          0         NA          0          0          0          0 
## 2012-11-19 2012-11-20 2012-11-21 2012-11-22 2012-11-23 2012-11-24 2012-11-25 
##          0          0          0          0          0          0          0 
## 2012-11-26 2012-11-27 2012-11-28 2012-11-29 2012-11-30 
##          0          0          0          0         NA</code></pre>
<p>Because of NA’s our median is meaningless. Let’s take a look of 5 minute intervals:</p>
<pre class="r"><code>five_min_intervals &lt;- filter(data,interval == 5)</code></pre>
<pre class="r"><code>five_min_intervals</code></pre>
<pre><code>##    steps       date interval   weekday
## 1     NA 2012-10-01        5    Monday
## 2      0 2012-10-02        5   Tuesday
## 3      0 2012-10-03        5 Wednesday
## 4      0 2012-10-04        5  Thursday
## 5      0 2012-10-05        5    Friday
## 6      0 2012-10-06        5  Saturday
## 7      0 2012-10-07        5    Sunday
## 8     NA 2012-10-08        5    Monday
## 9      0 2012-10-09        5   Tuesday
## 10    18 2012-10-10        5 Wednesday
## 11     0 2012-10-11        5  Thursday
## 12     0 2012-10-12        5    Friday
## 13     0 2012-10-13        5  Saturday
## 14     0 2012-10-14        5    Sunday
## 15     0 2012-10-15        5    Monday
## 16     0 2012-10-16        5   Tuesday
## 17     0 2012-10-17        5 Wednesday
## 18     0 2012-10-18        5  Thursday
## 19     0 2012-10-19        5    Friday
## 20     0 2012-10-20        5  Saturday
## 21     0 2012-10-21        5    Sunday
## 22     0 2012-10-22        5    Monday
## 23     0 2012-10-23        5   Tuesday
## 24     0 2012-10-24        5 Wednesday
## 25     0 2012-10-25        5  Thursday
## 26     0 2012-10-26        5    Friday
## 27     0 2012-10-27        5  Saturday
## 28     0 2012-10-28        5    Sunday
## 29     0 2012-10-29        5    Monday
## 30     0 2012-10-30        5   Tuesday
## 31     0 2012-10-31        5 Wednesday
## 32    NA 2012-11-01        5  Thursday
## 33     0 2012-11-02        5    Friday
## 34     0 2012-11-03        5  Saturday
## 35    NA 2012-11-04        5    Sunday
## 36     0 2012-11-05        5    Monday
## 37     0 2012-11-06        5   Tuesday
## 38     0 2012-11-07        5 Wednesday
## 39     0 2012-11-08        5  Thursday
## 40    NA 2012-11-09        5    Friday
## 41    NA 2012-11-10        5  Saturday
## 42     0 2012-11-11        5    Sunday
## 43     0 2012-11-12        5    Monday
## 44     0 2012-11-13        5   Tuesday
## 45    NA 2012-11-14        5 Wednesday
## 46     0 2012-11-15        5  Thursday
## 47     0 2012-11-16        5    Friday
## 48     0 2012-11-17        5  Saturday
## 49     0 2012-11-18        5    Sunday
## 50     0 2012-11-19        5    Monday
## 51     0 2012-11-20        5   Tuesday
## 52     0 2012-11-21        5 Wednesday
## 53     0 2012-11-22        5  Thursday
## 54     0 2012-11-23        5    Friday
## 55     0 2012-11-24        5  Saturday
## 56     0 2012-11-25        5    Sunday
## 57     0 2012-11-26        5    Monday
## 58     0 2012-11-27        5   Tuesday
## 59     0 2012-11-28        5 Wednesday
## 60     0 2012-11-29        5  Thursday
## 61    NA 2012-11-30        5    Friday</code></pre>
<p>These NA’s are problem. Average values of steps in 5 minute intervals.</p>
<pre class="r"><code>average_of_five_min_int &lt;- aggregate(five_min_intervals$steps, by = list(average = five_min_intervals$steps), FUN = mean, na.rm=TRUE)</code></pre>
<pre class="r"><code>average_of_five_min_int</code></pre>
<pre><code>##   average  x
## 1       0  0
## 2      18 18</code></pre>
<p>Average of five minute intervals:</p>
<pre class="r"><code>mean(five_min_intervals$steps, na.rm=TRUE)</code></pre>
<pre><code>## [1] 0.3396226</code></pre>
<p>Maximum steps of five minute intervals:</p>
<pre class="r"><code>max(five_min_intervals$steps,na.rm = TRUE)</code></pre>
<pre><code>## [1] 18</code></pre>
</div>
<div id="filling-nas" class="section level3" number="0.0.3">
<h3><span class="header-section-number">0.0.3</span> FILLING NA’S</h3>
<p>Let’s take a look at steps taken weekdays:</p>
<pre class="r"><code>steps_by_weekdays &lt;- aggregate(data$steps, by=list(weekday = data$weekday), FUN=sum, na.rm=TRUE)</code></pre>
<pre class="r"><code>names(steps_by_weekdays)= c(&quot;weekday&quot;,&quot;total_steps&quot;)</code></pre>
<pre class="r"><code>steps_by_weekdays[c(&#39;weekday&#39;,&#39;total_steps&#39;)]</code></pre>
<pre><code>##     weekday total_steps
## 1    Friday       86518
## 2    Monday       69824
## 3  Saturday       87748
## 4    Sunday       85944
## 5  Thursday       65702
## 6   Tuesday       80546
## 7 Wednesday       94326</code></pre>
<p>We see wednesday is the most steps taken day.</p>
<pre class="r"><code>g &lt;- ggplot(steps_by_weekdays,aes(weekday, total_steps))
g + geom_col(aes(colour=weekday)) </code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Let’s find the mean of steps taken each weekday. Let’s find how many days we have observed the taken steps</p>
<pre class="r"><code>length(unique(data$date))</code></pre>
<pre><code>## [1] 61</code></pre>
<p>Now let’s redefine our grouped data and see our average of steps in weekdays:</p>
<pre class="r"><code>average_weekdays &lt;- steps_by_weekdays
average_weekdays$total_steps &lt;- average_weekdays$total_steps/61
average_weekdays</code></pre>
<pre><code>##     weekday total_steps
## 1    Friday    1418.328
## 2    Monday    1144.656
## 3  Saturday    1438.492
## 4    Sunday    1408.918
## 5  Thursday    1077.082
## 6   Tuesday    1320.426
## 7 Wednesday    1546.328</code></pre>
<p>And how many intervals do we have in a day?</p>
<pre class="r"><code>length(unique(data$interval))</code></pre>
<pre><code>## [1] 288</code></pre>
<p>We can subset each interval and find mean of the steps take by intervals but we don’t have much information about intervals. We have too much NA for 5 minute intervals, so mean of them won’t be meaningful. That’s why we can fill NA’s with each weekday’s average step number by the interval. Let’s code what I meant:</p>
<pre class="r"><code>average_weekdays$total_steps &lt;- average_weekdays$total_steps / 288
average_weekdays</code></pre>
<pre><code>##     weekday total_steps
## 1    Friday    4.924750
## 2    Monday    3.974499
## 3  Saturday    4.994763
## 4    Sunday    4.892077
## 5  Thursday    3.739868
## 6   Tuesday    4.584813
## 7 Wednesday    5.369194</code></pre>
<p>But for sure we can’t have a 4.92 steps to take. We have two options here, Either we can round those numbers up or down according to which side they are close to, or we can distribute for ex 1418 steps to friday NA’s. I will take the first way.</p>
<pre class="r"><code>average_weekdays$total_steps &lt;- round(average_weekdays$total_steps)
average_weekdays</code></pre>
<pre><code>##     weekday total_steps
## 1    Friday           5
## 2    Monday           4
## 3  Saturday           5
## 4    Sunday           5
## 5  Thursday           4
## 6   Tuesday           5
## 7 Wednesday           5</code></pre>
<p>So for Mondays and Thursdays we should fill NA’S with 4 and other days we should fill NA’s with 5. Now let’s fill NA’s with those numbers:</p>
<pre class="r"><code>data_filled &lt;- data

for (i in 1:length(data_filled$steps)){
  if ((is.na(data_filled$steps[i])) &amp; (data_filled$weekday[i] == &quot;Friday&quot; | data_filled$weekday[i] == &quot;Saturday&quot; | data_filled$weekday[i] == &quot;Sunday&quot; | data_filled$weekday[i] == &quot;Tuesday&quot; | data_filled$weekday[i] == &quot;Wednesday&quot;)){
    data_filled$steps[i] &lt;- 5  }
  if ((is.na(data_filled$steps[i])) &amp; (data_filled$weekday[i] == &quot;Monday&quot; | data_filled$weekday[i] == &quot;Thursday&quot;)){
    data_filled$steps[i] &lt;- 4
  }
}</code></pre>
<p>Now let’s take a look our new data:</p>
<pre class="r"><code>head(data_filled)</code></pre>
<pre><code>##   steps       date interval weekday
## 1     4 2012-10-01        0  Monday
## 2     4 2012-10-01        5  Monday
## 3     4 2012-10-01       10  Monday
## 4     4 2012-10-01       15  Monday
## 5     4 2012-10-01       20  Monday
## 6     4 2012-10-01       25  Monday</code></pre>
<p>Mondays were NA and now we filled NA’s with 4 for Mondays. After imputing NA’s we should take a look our plots again. To calculate total steps taken in each day we will make groups again:</p>
<pre class="r"><code>steps_by_days &lt;- aggregate(data_filled$steps, by=list(date = data_filled$date), FUN=sum, na.rm=TRUE)
names(steps_by_days) &lt;- c(&quot;Date&quot;,&quot;Total_Steps&quot;)</code></pre>
<p>We created groups and let’s plot them:</p>
<pre class="r"><code>g &lt;- ggplot(steps_by_days,aes(Date,Total_Steps))
g + geom_col(aes(colour=Date))  +scale_x_date(date_breaks = &quot;5 days&quot;, date_labels = &quot;%d.%m&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>If you take a look of previous version of this plot you can see some bars are higher and most of the gaps are filled.</p>
<p>Now let’s compare weekdays and weekends steps taken. To do so we will create two different groups: weekdays_steps and weekend_steps</p>
<pre class="r"><code>weekdays_steps &lt;- aggregate(data_filled$steps[data_filled$weekday != &quot;Saturday&quot; &amp; data_filled$weekday != &quot;Sunday&quot;], by = list(date = data_filled$weekday[data_filled$weekday != &quot;Saturday&quot; &amp; data_filled$weekday != &quot;Sunday&quot;]), FUN = sum, na.rm=TRUE)
names(weekdays_steps) &lt;- c(&quot;Date&quot;,&quot;Total_Steps&quot;)

weekend_steps &lt;- aggregate(data_filled$steps[data_filled$weekday == &quot;Saturday&quot; | data_filled$weekday == &quot;Sunday&quot;], by = list(date = data_filled$weekday[data_filled$weekday == &quot;Saturday&quot; | data_filled$weekday == &quot;Sunday&quot;]), FUN = sum, na.rm=TRUE)
names(weekend_steps) &lt;- c(&quot;Date&quot;,&quot;Total_Steps&quot;)</code></pre>
<p>Let’s plot our groups in a panel plot:</p>
<pre class="r"><code>par(mfrow = c(1, 2))
options(scipen=999)
plot(weekdays_steps$Date, weekdays_steps$Total_Steps,xlab = &quot;Weekdays&quot;,
      ylab = &quot;Total Steps&quot;, ylim=(c(0,max(weekdays_steps$Total_Steps)+5000)))
plot(Total_Steps ~Date, data = weekend_steps,  xlab = &quot;Weekend&quot;,
      ylab = &quot;Total Steps&quot;, ylim =(c(0,max(weekend_steps$Total_Steps)+5000)))</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
